alias: Amy up at weird time
trigger:
    platform: state
    entity_id: input_select.amy_status
    to: 'standby'
condition:
    - condition: state
      entity_id: 'device_tracker.tyler_amyphone'
      state: 'home'
    - condition: time
      after: '03:00:00'
    - condition: sun
      before: sunrise
action:
    service: scene.turn_on
    entity_id: scene.living_room_off