# new 20 oct 2016 - uses tasker to trigger the morning wakeup routine
alias: amy alarming
trigger:
    platform: state
    entity_id: input_select.amy_status
    to: 'alarming'
condition:
  - condition: state
    entity_id: device_tracker.tyler_amyphone
    state: home
  - condition: sun
    before: sunrise
action:
  - service: scene.turn_on
    entity_id: scene.living_room_morning
  - service: scene.turn_on
    entity_id: scene.master_bath_bright_red