# Amy Sleep Tyler Ready

alias: amy ready for bed tyler is already ready
trigger:
    platform: state
    entity_id: input_select.amy_status
    to: 'sleeping'    
condition: 
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.tyler_status
      state: 'sleeping'
    - condition: state
      entity_id: 'device_tracker.tyler_tyler'
      state: 'not_home' 
action:
    service: script.nighttime_shutdown