# Turns the bathroom light off after 25minutes of turning on during the day
alias: quit leaving the bathroom light on
trigger:
    platform: state
    entity_id: light.master_bathroom
    to: 'on'
    for:
        minutes: 25
condition:
    condition: state
    entity_id: 'input_select.darkness_state'
    state: 'its_daytime'
action:
    service: scene.turn_on
    entity_id: scene.master_bath_off
