# Turn bug zapper off

alias: Turn Bug Zapper Off
trigger: 
    platform: sun
    event: sunrise
    offset: "01:00:00"
action:
  - service: switch.turn_off
    entity_id: switch.ge_unknown_type4f50_id3031_switch_2_0
  - service: input_select.select_option
    data:
      entity_id: input_select.bug_zapper_state
      option: 'bug_off'
  - service: input_select.select_option
    data:
      entity_id: input_select.darkness_state
      option: 'its_daytime'