# Turn bug zapper on

alias: Turn Bug Zapper On
trigger: 
    platform: sun
    event: sunset
    offset: "-01:00:00"
action:
  - service: switch.turn_on
    entity_id: switch.ge_unknown_type4f50_id3031_switch_2_0
  - service: input_select.select_option
    data:
      entity_id: input_select.bug_zapper_state
      option: 'bug_on'