# It's dark and it's daytime.

alias: It's Daytime But It's Dark - Exterior Lights On
trigger: 
    platform: state
    entity_id: binary_sensor.darkness_threshold_for_lights_on
    from: 'off'
    to: 'on'
    for:
      minutes: 10
condition:
  - condition: state
    entity_id: 'input_select.darkness_state'
    state: 'its_daytime'
action:
  - service: scene.turn_on
    entity_id: scene.exterior_lights_on