alias: Interior Lights On
trigger: 
    platform: sun
    event: sunset
    offset: "-00:35:00"
action:
  - service: scene.turn_on
    entity_id: scene.living_room_normal
  - service: scene.turn_on
    entity_id: scene.master_bedroom_on
  - service: scene.turn_on
    entity_id: scene.guest_bedroom_on