alias: Amy Wakes Up
trigger: 
    platform: time
    after: '06:00:00'
condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
    service: scene.turn_on
    entity_id: scene.living_room_morning