# If it starts raining, turn on exterior lights #

alias: rain_started
trigger:
    platform: state
    entity_id: sensor.dark_sky_precip
    state: 'rain'
    for:
        minutes: 10
condition: 
  condition: and
  conditions:
    - condition: state
      entity_id: 'input_select.darkness_state'
      state: 'its_daytime'
action:
    service: scene.turn_on
    entity_id: scene.exterior_lights_on