# If it stops raining and the sun is still up, turn the lights off #

alias: rain_stopped_sun_still_up
trigger:
    platform: state
    entity_id: sensor.dark_sky_precip
    state: '0'
    for:
        minutes: 10
condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'input_select.darkness_state'
        state: 'its_daytime'
      - condition: state
        entity_id: 'input_select.house_status'
        state: 'awake'
action:
    service: scene.turn_on
    entity_id: scene.exterior_lights_off