# Tyler Sleep Amy Not Ready

alias: tyler ready for bed
trigger:
    platform: state
    entity_id: input_select.tyler_status
    to: 'sleeping'
condition:
    - condition: state
      entity_id: input_select.amy_status
      state: 'standby'
    - condition: state
      entity_id: device_tracker.tyler_amyphone
      state: 'home'
    - condition: state
      entity_id: device_tracker.tyler_tyler
      state: 'home'
action:
    service: homeassistant.turn_off
    entity_id: light.bedroom__tyler